/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IntentVouchStatusImport } from './routes/intent/vouch-status'
import { Route as IntentVouchGoalImport } from './routes/intent/vouch-goal'

// Create Virtual Routes

const DevelopersLazyImport = createFileRoute('/developers')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DevelopersLazyRoute = DevelopersLazyImport.update({
  path: '/developers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/developers.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const IntentVouchStatusRoute = IntentVouchStatusImport.update({
  path: '/intent/vouch-status',
  getParentRoute: () => rootRoute,
} as any)

const IntentVouchGoalRoute = IntentVouchGoalImport.update({
  path: '/intent/vouch-goal',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersLazyImport
      parentRoute: typeof rootRoute
    }
    '/intent/vouch-goal': {
      id: '/intent/vouch-goal'
      path: '/intent/vouch-goal'
      fullPath: '/intent/vouch-goal'
      preLoaderRoute: typeof IntentVouchGoalImport
      parentRoute: typeof rootRoute
    }
    '/intent/vouch-status': {
      id: '/intent/vouch-status'
      path: '/intent/vouch-status'
      fullPath: '/intent/vouch-status'
      preLoaderRoute: typeof IntentVouchStatusImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/developers': typeof DevelopersLazyRoute
  '/intent/vouch-goal': typeof IntentVouchGoalRoute
  '/intent/vouch-status': typeof IntentVouchStatusRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/developers': typeof DevelopersLazyRoute
  '/intent/vouch-goal': typeof IntentVouchGoalRoute
  '/intent/vouch-status': typeof IntentVouchStatusRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/developers': typeof DevelopersLazyRoute
  '/intent/vouch-goal': typeof IntentVouchGoalRoute
  '/intent/vouch-status': typeof IntentVouchStatusRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/developers' | '/intent/vouch-goal' | '/intent/vouch-status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/developers' | '/intent/vouch-goal' | '/intent/vouch-status'
  id:
    | '__root__'
    | '/'
    | '/developers'
    | '/intent/vouch-goal'
    | '/intent/vouch-status'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DevelopersLazyRoute: typeof DevelopersLazyRoute
  IntentVouchGoalRoute: typeof IntentVouchGoalRoute
  IntentVouchStatusRoute: typeof IntentVouchStatusRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DevelopersLazyRoute: DevelopersLazyRoute,
  IntentVouchGoalRoute: IntentVouchGoalRoute,
  IntentVouchStatusRoute: IntentVouchStatusRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/developers",
        "/intent/vouch-goal",
        "/intent/vouch-status"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/developers": {
      "filePath": "developers.lazy.tsx"
    },
    "/intent/vouch-goal": {
      "filePath": "intent/vouch-goal.tsx"
    },
    "/intent/vouch-status": {
      "filePath": "intent/vouch-status.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
